# -*- coding: utf-8 -*-
VER = {
2:("CONSERVAR-INT","Riesgo total alto asociado a fuste inclinado y daños mecánicos (heridas, ramas quebradas, poda inadecuada), no a inestabilidad de anclaje; caída Media. Ejemplar pequeño (D=6,3 cm; 3,2 m). Poda de reequilibrio, tratamiento de heridas y manejo de epífitas."),
3:("CONSERVAR","Buen estado estructural (fuste, corteza y hojas buenos); riesgo y caída bajos. Retirar cuerdas del fuste y poda ligera de formación."),
4:("CONSERVAR-INT","Riesgo medio por fuste torcido, copa irregular y cima mala; caída Media. Especie nativa de valor ornamental. Poda de saneamiento y formación; tratar el descortezamiento."),
5:("CONSERVAR-INT","Condición fitosanitaria deficiente (hongos, exudados, pústulas, pudrición de ramas, ápice muerto), pero riesgo de CAÍDA BAJO por porte moderado (9,1 m) y raíz buena. Poda sanitaria, tratamiento fungicida, manejo de epífitas y monitoreo."),
6:("CONSERVAR-INT","Riesgo alto por afección foliar y de cima (hojas y cima malas, ápice muerto) y fuste inclinado; caída Media. Árbol joven-pequeño (D=19,7 cm; 7,4 m), recuperable. Poda sanitaria, fertilización y tratamiento; monitorear evolución."),
7:("DERRIBO","Único ejemplar con riesgo de CAÍDA ALTO y recomendación de derribo en campo. Es el árbol de mayor porte del parque (D=118,2 cm; 27,1 m), con copa amplia y poco simétrica —gran brazo de palanca frente a los fuertes vientos de la zona— exudados de resina (indicador de estrés/patología del fuste) y ubicación junto a los baños (máxima concurrencia de personas). La probabilidad de fallo combinada con la alta exposición vuelve inaceptable el riesgo. Se recomienda DERRIBO técnico controlado, previa verificación instrumental (resistógrafo/tomografía) si se dispone del equipo."),
8:("CONSERVAR-INT","Caída y riesgo Medios, pero RAÍZ en MAL estado en un árbol alto (17,8 m): punto crítico de anclaje. Poda de aligeramiento/reducción de la vela para disminuir la carga de viento e inspección radicular; si se confirma pérdida de anclaje, reevaluar derribo. Monitoreo PRIORITARIO."),
9:("CONSERVAR","Estructura y anclaje buenos; riesgo y caída bajos. Retiro de clavos/alambres y mantenimiento."),
10:("CONSERVAR","Ejemplar alto (20,7 m) en buen estado general, raíz buena y caída baja. Mantenimiento menor: retiro de clavos/alambres y manejo de epífitas."),
11:("CONSERVAR-INT","Mayor VALOR de riesgo del inventario (2,97), pero originado por daño a infraestructura por raíces (Alto) e inclinación en espacio estrecho, NO por deterioro estructural: fuste, ramas, hojas y cima BUENOS. Especie NATIVA (nogal andino). Poda de reequilibrio y manejo de raíz (barreras / reparación de adoquín); no procede derribo."),
12:("CONSERVAR","Buen estado; riesgo y caída bajos. Poda menor y tratamiento de heridas."),
13:("CONSERVAR-INT","Buen anclaje (raíz buena) y caída baja. Poda ligera, manejo de epífitas y retiro de objetos extraños."),
14:("CONSERVAR","Palma en buen estado; riesgo mínimo. Mantenimiento (retiro de hojas secas)."),
15:("CONSERVAR-INT","Riesgo alto por fuste MUY inclinado en espacio estrecho y daño de raíz a infraestructura (Alto); caída Media. Poda de reequilibrio de copa para reducir carga en el lado inclinado y VIGILANCIA de la inclinación; si progresa, reevaluar."),
16:("CONSERVAR","Ejemplar joven en buen estado; riesgo mínimo. Mantenimiento."),
17:("CONSERVAR","Buen estado general; riesgo mínimo. Mantenimiento."),
18:("CONSERVAR","Riesgo bajo pese a fuste torcido; caída baja. Poda de formación y tratamiento de heridas."),
19:("CONSERVAR-INT","Riesgo bajo; cima mala y presencia de hongos. Poda sanitaria y manejo."),
20:("CONSERVAR","Riesgo bajo, buen anclaje. Poda menor y manejo de epífitas."),
21:("CONSERVAR-INT","Especie NATIVA (molle). Riesgo alto por fuste MUY inclinado; caída Media, estructura buena (fuste y corteza buenos). Poda de reequilibrio y VIGILANCIA de la inclinación."),
22:("CONSERVAR-INT","Riesgo alto por inclinación y copa irregular; caída Media, fuste bueno. Poda de reequilibrio y de saneamiento."),
23:("CONSERVAR","Palma en buen estado; riesgo mínimo. Mantenimiento."),
24:("CONSERVAR-INT","Fuste bueno y raíz buena → riesgo de CAÍDA no crítico (Media); el problema es la afectación a construcciones, circulación y raíces (Alto) por su ubicación en esquina/espacio estrecho con raíces descubiertas. Corresponde manejo de raíz (barreras, reparación de adoquín) y poda, NO derribo. Caso típico de daño al ornato con árbol estructuralmente sano."),
25:("CONSERVAR-INT","Riesgo alto por fuste muy inclinado; caída Media, ejemplar pequeño (D=7,6 cm). Poda de reequilibrio y tratamiento de heridas/descortezamiento."),
}
